const menulogos = (prefix) => {
  return`
╭──━─── ❀۝❀ ───━──╮
│        ⬕•𝑴𝒆𝒏𝒖 𝑫𝒆 𝑳𝒐𝒈𝒐𝒔•⬔
├──━─── ❀۝❀ ───━──╯
│
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}transformer (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}narutologo (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}thunderv2 (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}thunder (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}lobometal (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}glitch (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}america (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}demongreen (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}metalgold (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}crossfire (txt)  
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}shadow (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}wetglass (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}butterfly (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}grass (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}logogame (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}goldplay (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}silverplay (txt)  
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}folha (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}folha2 (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}folha3 (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}folha4 (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}folha5 (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neondevil (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}show (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}bracelet (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}placa (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}copo (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}papel (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}madeira (txt)     
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}grafity (txt)     
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}toxic (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}harryp (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}glitch (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}wooden (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}romantic (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}Gold (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neon (txt) 
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neon2 (txt)
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neon3 (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neon4 (txt)     
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}comporn (txt)     
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}comentarioL (txt) 
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}8bit (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}cemiterio (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}googlelogo (txt)  
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}grass (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}flower (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}batle (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}coffe (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}coffe2 (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}pubg (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}horror (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}fire (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}stone (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}break (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}hallowen (txt)    
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}vidro (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}carbon (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}metalblue (txt)   
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}pink (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}colaq (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}ossos (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}blood (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}areia (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}natal (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}style (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}neve (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}pornhub (txt)     
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}space (txt)       
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}jokerlogo (txt)  
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}love (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}larva (txt)        
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}luxury (txt)      
│ ♡ۣۜۜ፝͜͜͡͡✿➤ ${prefix}steel (txt)  
│
╰❑➤─| 𝐌𝐀𝐍𝐔𝐄𝐋𝐀 ⊱✿⊰ 𝙱𝙾𝚃 |─➤✿°࿐`
}
exports.menulogos = menulogos
